# Travis-CI setup for simple-speak | © Nick Freear | License: MIT.

language: node_js
node_js:
  - "4"
  #- "6"
  - "7"

git:
  depth: 8

script:
  - npm run build
  - npm test

after_script:
  - ls -alh build/
  #- node test/configure-test.js
  cat build/simple-speak.min.js

# End.
