# Travis-CI setup for simple-speak | © Nick Freear | License: MIT.

language: node_js

node_js: 7

git:
  depth: 8

before_script: npm run build

script: npm test

after_script:
  - ls -alh dist/
  #- node test/configure-test.js
  - cat dist/simple-speak.min.js

# End.
